### ISSUE TITLE
i need help！！！

### ISSUE THREAD

**Issue by ultracxx1997** [malllabiisc/WordGCN#33]
why i will have this question？
```
Traceback (most recent call last):
  File "D:\environment\Anaconda\lib\logging\config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
  File "D:\environment\Anaconda\lib\logging\config.py", line 735, in configure_handler
    result = factory(**kwargs)
  File "D:\environment\Anaconda\lib\logging\__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "D:\environment\Anaconda\lib\logging\__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'D:\\workspace\\WordGCN-master\\WordGCN-master\\log\\test_run_15_06_2020_08:32:34'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/workspace/WordGCN-master/WordGCN-master/syngcn.py", line 592, in <module>
    model = SynGCN(args)
  File "D:/workspace/WordGCN-master/WordGCN-master/syngcn.py", line 439, in __init__
    self.logger = get_logger(self.p.name, self.p.log_dir, self.p.config_dir)
  File "D:\workspace\WordGCN-master\WordGCN-master\helper.py", line 66, in get_logger
    logging.config.dictConfig(config_dict)
  File "D:\environment\Anaconda\lib\logging\config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "D:\environment\Anaconda\lib\logging\config.py", line 570, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'file_handler'

Process finished with exit code 1

```

**Comment by ultracxx1997** [comment]
my system is windows10, IDE is pycharm, is anything wrong?

**Comment by ultracxx1997** [comment]
`#	config_dict['handlers']['file_handler']['filename'] = log_dir + name.replace('/', '-')`
when the defined name of file is replace,the error will happened
